del "*.suo" /S/Q/F/A
del "*.csproj.user" /S/Q/F/A
rd "ner_ru.web.demo\bin" /S/Q
rd "ner_ru.web.demo\obj" /S/Q
rd "ner_ru.web.demo\(logs)" /S/Q
rd "ner_ru.console.demo\bin" /S/Q
rd "ner_ru.console.demo\obj" /S/Q
rd "captcha\bin" /S/Q
rd "captcha\obj" /S/Q
rd "crfsuite.net\bin" /S/Q
rd "crfsuite.net\obj" /S/Q
rd "lingvo.core\bin" /S/Q
rd "lingvo.core\obj" /S/Q
rd "ner-crf.net\bin" /S/Q
rd "ner-crf.net\obj" /S/Q
rd "SentSplitter\bin" /S/Q
rd "SentSplitter\obj" /S/Q
